### ISSUE TITLE
Import genéricos

### ISSUE THREAD

**Issue by osmarbraz** [LeonardoSchmittK/a3prog-crud-ferramentas#5]
Evite o uso de importes genéricos import java.sql.*;
Coloque import diretamente para as classes.
Revise a classe src/main/java/dao/EmprestimoDAO.java e outras.

**Comment by LeonardoSchmittK** [comment]
Retirado import genérico da classe src/main/java/dao/EmprestimoDAO.java, e adicionado imports específicos
